# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту daervia@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -daervia@gmail.com
    on_success: never # default: change
    on_failure: always # defa,ult: always

    env:
      global:
        - CODECOV_TOKEN="e969508f-2f53-4d7c-9b98-e14b7c35da12"